name: Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install

      - name: Build Mac
        run: pnpm build:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_DRAFT: true
          ELECTRON_BUILDER_PUBLISH: never

      - name: Subir DMG
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: dist/*.dmg

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install

      - name: Build Windows
        run: pnpm build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_DRAFT: true
          ELECTRON_BUILDER_PUBLISH: never

      - name: Subir EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*.exe
